python program.py distloc
python program.py distpop
python program.py distpop2
python program.py distgdp
python program.py distgdp2
python program.py distpopgdp
python program.py distpopgdp2
python program.py distpopratio
python program.py distgdpratio
python program.py distpopgdpratio
python program.py distpopgdpratio2
